#Turn WorldGrowth off.
disable-plugin: false





###############
#Miscellaneous#
###############

#Locale for WorldGrowth messages.
  #Rewrite 'en.properties' if your language has not been added yet.
locale: "en"
  #Help me support more languages by submitting translations: https://discord.gg/txJDdYcRV6

#If empty, WorldGrowth will affect all worlds.
  #To disable the plugin completely, scroll to the top of this file and set 'disable-plugin' to true.
restrict-plugin-to-worlds:
#  - "world"
#  - "world_nether"
#  - "world_the_end"