#Turn WorldGrowth off.
disable-plugin: false

#Guide: https://github.com/lichenaut/WorldGrowth/blob/main/README.md
  #Choosing a world seed is recommended, unless you want to risk being trapped in the desert! ;)

################
#World Settings#
################

#If "border-center" is set, it will become the world's spawn point, and the world border will be centered around it.
  #If "border-center" is not set, the world's spawn point will be used as the center of the world border.
worlds:
  world:
    main: true
    name: "world"
    #border-center: "0 64 0"
    start-size: 32
    max-size: 16384
    growth-multiplier: 8
  world_nether:
    name: "world_nether"
    #border-center: "0 64 0"
    start-size: 4
    max-size: 16384
    growth-multiplier: 1
  world_the_end:
    name: "world_the_end"
    #border-center: "0 64 0"
    start-size: 32
    max-size: 16384
    growth-multiplier: 8


#################
#Global Settings#
#################

#The amount of blocks the diameter of the world border will increase by per growth (times the world's growth multiplier).
growth-size: 4

#The maximum amount of blocks the main world border can grow per hour. Responsible for the world borders of all worlds.
  #Events convert to zero points when the maximum is reached.
max-block-growth-per-hour: 96

#The starting amount of points required to trigger a growth.
starting-growth-quota: 8

#The amount of points required to trigger a growth will increase by this amount each growth.
increment-growth-quota-by: 8

#The maximum amount of points required to trigger a growth.
max-growth-quota: 1024


############################
#Unification Event Settings#
############################

#If true, online players will be able to vote to, when the point quota for world growth is met:
  #1. Expand the world borders as usual (this is the default vote choice).
  #2. Make the borders of all worlds the size of the largest world border (up until their 'max-size's), where points are converted into duration.
unification-enabled: true
  #This is mainly to expand the world border of The Nether for temporary structure access in the early game.

#Each point adds this many ticks to the duration of the unification event.
ticks-per-point: 1200

#The percentage of online players required to vote for the unification event for it to occur.
voting-threshold: 66.66


###############
#Miscellaneous#
###############

#WorldGrowth will store data in its plugin folder's SQLite database if a MySQL database is not provided.
database-url: #"localhost:3306/example_db"
database-user: #"root"
database-password: #""
  #https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing#connections--core_count--2--effective_spindle_count
database-max-pool-size: 8

#Locale for WorldGrowth messages.
  #Rewrite 'en.properties' if your language has not been added yet.
locale: "en"
  #Help me support more languages by submitting translations: https://discord.gg/txJDdYcRV6

#If true, WorldGrowth will broadcast point gain boost event starts and ends.
broadcast-boosts: true


##############
#Point System#
##############

#Event list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/Event.html
  #You cannot add event types.

events:
  #BlockEvent
  bell-resonate:
  bell-ring:
  block-break:
    quota: 128
    points: 1
  block-burn:
  block-can-build:
  block-cook:
    quota: 128
    points: 1
  block-damage-abort:
  block-damage:
  block-dispense:
  block-dispense-armor:
  block-drop-item:
  block-exp:
    quota: 24
    points: 1
  block-explode:
  block-fade:
  block-fertilize:
    quota: 576
    points: 1
  block-from-to:
  block-grow:
    quota: 1024
    points: 1
  block-ignite:
  block-multi-place:
    quota: 256
    points: 1
  block-physics:
  block-piston:
  block-place:
    quota: 256
    points: 1
  block-receive-game:
  block-redstone:
  block-shear-entity:
    quota: 48
    points: 1
  brew:
    quota: 16
    points: 1
  brewing-stand-fuel:
  brewing-start:
  campfire-start:
  cauldron-level-change:
  fluid-level-change:
  furnace-burn:
  furnace-extract:
  furnace-smelt:
  furnace-start-smelt:
  hopper-inventory-search:
  leaves-decay:
    quota: 256
    points: 1
  moisture-change:
  note-play:
  sculk-bloom:
  sign-change:
  sponge-absorb:
  tnt-prime:

  #EntityEvent
  area-effect-cloud-apply:
    quota: 480
    points: 1
  arrow-body-count-change:
    quota: 32
    points: 1
  bat-toggle-sleep: #Note 1: I'm giving this event a quota out of pity for it lol
    quota: 512
    points: 1
  creature-spawn:
    quota: 1024
    points: 1
  creeper-power:
    quota: 1
    points: 4
  ender-dragon-change-phase:
    quota: 2
    points: 1
  entity-air-change:
  entity-breed:
    quota: 16
    points: 1
  entity-change-block:
  entity-combust:
  entity-combust-by-block:
  entity-combust-by-entity:
    quota: 8
    points: 1
  entity-damage:
  entity-damage-by-block:
    quota: 32
    points: 1
  entity-damage-by-entity:
    quota: 16
    points: 1
  entity-death:
    quota: 512
    points: 1
  entity-dismount:
  entity-drop-item:
  entity-enter-block:
    quota: 16
    points: 1
  entity-enter-love-mode:
  entity-exhaustion:
    quota: 1024
    points: 1
  entity-explode:
    quota: 215
    points: 1
  entity-interact:
  entity-knockback:
  entity-mount:
  entity-pickup-item:
  entity-place:
    quota: 256
    points: 1
  entity-portal-enter:
    quota: 32
    points: 1
  entity-pose-change:
  entity-potion-effect:
    quota: 215
    points: 1
  entity-regain-health:
    quota: 512
    points: 1
  entity-resurrect:
    quota: 1
    points: 1
  entity-shoot-bow:
    quota: 128
    points: 1
  entity-spawn:
  entity-spell-cast:
    quota: 4
    points: 1
  entity-tame:
    quota: 2
    points: 1
  entity-target:
  entity-teleport:
    quota: 32
    points: 1
  entity-toggle-glide:
  entity-toggle-swim:
  entity-transform:
    quota: 32
    points: 1
  entity-unleash:
  exp-bottle:
    quota: 32
    points: 1
  explosion-prime:
  firework-explode:
    quota: 128
    points: 1
  food-level-change:
  horse-jump:
  item-despawn:
  item-merge:
  item-spawn:
  lingering-potion-splash:
    quota: 16
    points: 1
  piglin-barter:
    quota: 24
    points: 1
  pig-zap:
  pig-zombie-anger:
    quota: 32
    points: 1
  player-death:
    quota: 8
    points: 1
  potion-splash:
    quota: 16
    points: 1
  projectile-hit:
  projectile-launch:
  sheep-dye-wool:
    quota: 256
    points: 1
  sheep-regrow-wool:
    quota: 48
    points: 1
  slime-split:
  spawner-spawn:
  strider-temperature-change:
  villager-acquire-trade:
    quota: 8
    points: 1
  villager-career-change:
  villager-replenish-trade:
    quota: 16
    points: 1

  #PlayerEvent
  async-player-chat:
  player-advancement-done:
    quota: 2
    points: 1
  player-animation:
  player-bed-enter:
  player-bed-leave:
  player-bucket:
  player-bucket-entity:
  player-changed-main-hand:
  player-changed-world:
    quota: 32
    points: 1
  player-channel:
  player-command-send:
  player-drop-item:
  player-edit-book:
  player-egg-throw:
    quota: 128
    points: 1
  player-exp-change:
    quota: 1024
    points: 1
  player-fish: #Note 2: This only counts the CAUGHT_FISH state.
    quota: 16
    points: 1
  player-game-mode-change:
  player-harvest-block:
    quota: 128
    points: 1
  player-hide-entity:
  player-interact:
  player-interact-entity:
  player-item-break:
    quota: 4
    points: 1
  player-item-consume:
    quota: 128
    points: 1
  player-item-damage:
  player-item-held:
  player-item-mend:
  player-join:
  player-kick:
  player-level-change:
  player-locale-change:
  player-login:
  player-move:
  player-quit:
  player-recipe-book-click:
  player-recipe-book-settings-change:
  player-recipe-discover:
    quota: 64
    points: 1
  player-resource-pack-status:
  player-respawn:
  player-riptide:
    quota: 32
    points: 1
  player-shear-entity:
    quota: 32
    points: 1
  player-show-entity:
  player-spawn-location:
  player-statistic-increment: #Note 3: I filtered this down to make it reasonable for a quota of 256, but it's called too much to be worth it, imo.
  player-swap-hand-items:
  player-take-lectern-book:
  player-teleport:
  player-toggle-flight:
  player-toggle-sneak:
  player-toggle-sprint:
  player-velocity:

  #CustomEvent
